/**
 * Trial drip email copy and the sales notification template.
 *
 * Wire these into the Gmail SMTP sender + Cloud Scheduler cron. Each email
 * supports simple {{handlebars}} tokens that the dispatcher must replace.
 *
 * Available tokens:
 *   {{firstName}}        e.g. "Aman"
 *   {{fullName}}         e.g. "Dr. Aman Kulkarni"
 *   {{role}}             e.g. "Doctor"
 *   {{specialty}}        e.g. "Internal Medicine" (may be empty for non-doctors)
 *   {{hospitalOrCompany}} e.g. "City Care Clinic"
 *   {{country}}          e.g. "India"
 *   {{loginUrl}}         e.g. "https://app.jatayuhealth.com"
 *   {{trialEndsOn}}      formatted date, e.g. "10 May 2026"
 *   {{daysLeft}}         number, e.g. "1"
 *   {{quickStartUrl}}    e.g. "https://jatayuhealth.com/product#quickstart"
 *   {{caseStudyUrl}}     KEM case study URL
 *   {{walkthroughUrl}}   "/contact"
 *   {{salesEmail}}       sales@jatayuhealth.com
 *   {{calendarUrl}}      Cal.com self-hosted scheduling URL when configured
 *   {{unsubscribeUrl}}   one-click unsubscribe (legally required)
 *
 * Tone: doctor-to-doctor, India-proud, tech-confident, clinically precise.
 * No em-dashes. No "AI-powered". No "revolutionize" / "disrupt".
 */

export type TrialEmail = {
  id: string;
  /** Days after signup. 0 = sent immediately on signup. */
  sendOnDay: number;
  subject: string;
  preheader: string;
  /** Plain-text body (one paragraph per array element). HTML version is generated by the dispatcher. */
  body: string[];
  /** Primary call to action shown as a button + repeated in body. */
  cta: { label: string; url: string };
};

export const trialDripEmails: TrialEmail[] = [
  {
    id: "day-0-welcome",
    sendOnDay: 0,
    subject: "Your VoiceDocAI trial is ready, {{firstName}}",
    preheader:
      "Your account is live for 7 days. Here is the 3-minute quick start.",
    body: [
      "Hi {{firstName}},",
      "Your 7-day VoiceDocAI trial is active until {{trialEndsOn}}. You can sign in at {{loginUrl}} with the email you used to register.",
      "If you have 3 minutes, the quick start at {{quickStartUrl}} walks through your first multilingual capture and verification. It is the fastest way to feel the difference in a real consultation.",
      "If anything is unclear, reply to this email. It reaches a real person on our team.",
      "Looking forward to your feedback,",
      "Team Jatayu",
    ],
    cta: { label: "Open VoiceDocAI", url: "{{loginUrl}}" },
  },
  {
    id: "day-1-onboarding",
    sendOnDay: 1,
    subject: "One small habit that makes VoiceDocAI feel automatic",
    preheader:
      "How clinicians in our pilots got fluent on day two.",
    body: [
      "Hi {{firstName}},",
      "Most clinicians who stick with VoiceDocAI do one thing on day two: they speak the way they would to a colleague, not to a machine.",
      "You do not need to slow down. You do not need to switch language mid-consultation. The model was trained on real Indian clinics in Hindi, Marathi, and English, including mixed conversations.",
      "If you want to try a structured 5-minute exercise, we put one together at {{quickStartUrl}}. It uses a sample patient narrative you can speak in your own voice.",
      "Warmly,",
      "Team Jatayu",
    ],
    cta: { label: "Try the 5-minute exercise", url: "{{quickStartUrl}}" },
  },
  {
    id: "day-3-use-case",
    sendOnDay: 3,
    subject: "Where clinicians save the most time, by specialty",
    preheader:
      "Discharge summaries, OT notes, radiology narratives. Pick one to try this week.",
    body: [
      "Hi {{firstName}},",
      "If you are looking for a high-leverage place to use VoiceDocAI this week, here is what showed up across the KEM Hospital pilot:",
      "Discharge summaries: longest narratives, biggest time savings.",
      "OT notes: structured fields take well to dictation, and reviewers approve faster.",
      "Radiology reports: structured impressions and recommendations land cleanly in HMIS.",
      "Pick one and run with it for two days. Most clinicians notice the change by the third encounter.",
      "Warmly,",
      "Team Jatayu",
    ],
    cta: { label: "See the KEM pilot summary", url: "{{caseStudyUrl}}" },
  },
  {
    id: "day-5-evidence",
    sendOnDay: 5,
    subject: "How a 100-bed hospital evaluated VoiceDocAI",
    preheader:
      "Real pilot, real numbers. Read it before you decide.",
    body: [
      "Hi {{firstName}},",
      "If you are weighing whether VoiceDocAI fits your practice, the KEM Hospital pilot is the most useful artifact we can share. It documents what we measured, who participated, and where the system fell short.",
      "It is short and honest. We do not stretch the numbers.",
      "If your decision involves a hospital IT team, our Security and Compliance page is also linked at the end of the case study so you can forward it directly.",
      "Warmly,",
      "Team Jatayu",
    ],
    cta: { label: "Read the KEM pilot", url: "{{caseStudyUrl}}" },
  },
  {
    id: "day-6-trial-ending",
    sendOnDay: 6,
    subject: "Your VoiceDocAI trial ends tomorrow",
    preheader:
      "If it is helping, lock it in. If not, tell us what was missing.",
    body: [
      "Hi {{firstName}},",
      "Your trial ends tomorrow, {{trialEndsOn}}. A few options from here:",
      "If VoiceDocAI is earning its keep, reply to this email with the word 'continue' and we will set up the right plan for {{hospitalOrCompany}}.",
      "If you would prefer a 20-minute walkthrough before deciding, you can book directly at {{walkthroughUrl}}.",
      "If it did not work for you, please tell us why. We read every reply, and our roadmap moves on the back of clinician feedback.",
      "Either way, thank you for trying it.",
      "Warmly,",
      "Team Jatayu",
    ],
    cta: { label: "Book a 20-minute walkthrough", url: "{{walkthroughUrl}}" },
  },
  {
    id: "day-7-expiry",
    sendOnDay: 7,
    subject: "Your trial closed today. The door is still open.",
    preheader:
      "Your account is paused, not deleted. Here is what to do next.",
    body: [
      "Hi {{firstName}},",
      "Your VoiceDocAI trial closed today. Your account is paused, not deleted, so you can pick up where you left off if you decide to come back.",
      "If you want to continue, reply to this email or book a short call at {{walkthroughUrl}}. We will recommend the right plan based on how you used the trial.",
      "If you have decided VoiceDocAI is not for you right now, no problem. We would still appreciate one line of feedback.",
      "Either way, thank you for the time you put in.",
      "Warmly,",
      "Team Jatayu",
    ],
    cta: { label: "Continue with VoiceDocAI", url: "{{walkthroughUrl}}" },
  },
];

/**
 * Sales notification: sent to {{salesEmail}} immediately on every trial signup.
 * Plain text on purpose so it threads cleanly in Gmail.
 */
export const salesNotification = {
  to: "{{salesEmail}}",
  subject: "New trial: {{fullName}} from {{hospitalOrCompany}} ({{country}})",
  preheader: "New VoiceDocAI trial signup, action recommended within 1 business day.",
  body: [
    "New trial signup just landed.",
    "Name: {{fullName}}",
    "Role: {{role}}",
    "Specialty: {{specialty}}",
    "Hospital or company: {{hospitalOrCompany}}",
    "Country: {{country}}",
    "Work email: {{workEmail}}",
    "Phone: {{phone}}",
    "Trial ends on: {{trialEndsOn}}",
    "",
    "Recommended next step: send a personal welcome from your inbox within one business day. Reference their hospital and role. Do not pitch.",
    "",
    "CRM record: {{crmRecordUrl}}",
  ],
};

/** Confirmation we show on the trial page after a successful submit. */
export const trialFormSuccessCopy = {
  title: "You are in.",
  body:
    "We just sent your account details to your work email. If you do not see it within a few minutes, check spam, then reply to sales@jatayuhealth.com and we will sort it.",
  cta: { label: "Open my inbox guidance", href: "/product" },
};
