#!/usr/bin/env bash
#
# sync-prod-schema.sh
# -------------------
# One-shot schema sync: starts the local Next.js dev server with the supplied
# DATABASE_URI, triggers Payload init with a single HTTP request (which causes
# drizzle-kit to push any missing tables and columns), then exits.
#
# Why a shell script rather than a tsx script:
#   Payload v3.84's `loadEnv` helper does an ESM default-import of `@next/env`
#   which fails under tsx + Node 20 (TypeError: import_env.default is
#   undefined). The dev-server path doesn't hit that code, so we drive Payload
#   from outside via the running dev server.
#
# Usage:
#   DATABASE_URI='postgres://user:pass@host:5432/db?sslmode=require' \
#     npm run sync-prod-schema
#
# Pull the prod URI from the Azure key vault:
#   az keyvault secret show --vault-name jatayu-prod-kv-fbd5 \
#     --name database-uri --query value -o tsv
#
# Exits 0 on success, non-zero on any failure. Operations are additive — the
# script never drops tables or columns; destructive changes need a hand-
# written migration.

set -euo pipefail

# ---- preconditions ----------------------------------------------------------
if [[ -z "${DATABASE_URI:-}" ]]; then
  echo "❌ DATABASE_URI is required." >&2
  echo "   Example:" >&2
  echo "   DATABASE_URI='postgres://user:pass@host:5432/db?sslmode=require' npm run sync-prod-schema" >&2
  exit 1
fi

# Redact the password before printing.
SAFE_URI="${DATABASE_URI//:*@/:****@}"
echo "→ Syncing schema against ${SAFE_URI}"

# Where the repo root sits, regardless of where this script is invoked from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Next.js env-file loading order: process.env > .env.development.local >
# .env.local > .env.development > .env. We need DATABASE_URI to win over
# the local-dev value in .env.local, but Payload's loadEnv path reloads env
# files at request time and overwrites process.env — so a shell-level
# `DATABASE_URI=... npm run dev` is not enough. We write a temporary
# .env.development.local (higher precedence than .env.local), then delete
# it in the cleanup trap so it never ends up checked in.
TEMP_ENV_FILE="${REPO_ROOT}/.env.development.local"
ALREADY_HAD_TEMP_ENV=0
if [[ -e "${TEMP_ENV_FILE}" ]]; then
  ALREADY_HAD_TEMP_ENV=1
  echo "❌ ${TEMP_ENV_FILE} already exists. Refusing to overwrite." >&2
  echo "   Move it aside before re-running this script." >&2
  exit 1
fi
{
  echo "# AUTO-GENERATED by scripts/sync-prod-schema.sh — deleted on exit."
  echo "DATABASE_URI=${DATABASE_URI}"
} > "${TEMP_ENV_FILE}"

# Install the cleanup trap right after writing the temp env file, so the file
# is removed even if dev-server startup fails. DEV_PID is checked with the
# `${DEV_PID:-}` guard since cleanup may fire before it is set.
cleanup() {
  if [[ -n "${DEV_PID:-}" ]] && kill -0 "${DEV_PID}" 2>/dev/null; then
    echo "→ Stopping dev server (pid ${DEV_PID})"
    kill "${DEV_PID}" 2>/dev/null || true
    wait "${DEV_PID}" 2>/dev/null || true
  fi
  if [[ "${ALREADY_HAD_TEMP_ENV}" -eq 0 ]] && [[ -e "${TEMP_ENV_FILE}" ]]; then
    rm -f "${TEMP_ENV_FILE}"
  fi
}
trap cleanup EXIT

# ---- start the dev server ---------------------------------------------------
# Use a temp log file so we can wait for specific markers.
LOG_FILE="$(mktemp -t jatayu-sync-schema.XXXXXX.log)"
PORT="${PORT:-3001}"

# We picked a non-default port (3001) so this never collides with a long-
# running `npm run dev` someone forgot about on 3000.
echo "→ Starting Next.js dev server on port ${PORT} (logs: ${LOG_FILE})"
DATABASE_URI="${DATABASE_URI}" PORT="${PORT}" npm run dev > "${LOG_FILE}" 2>&1 &
DEV_PID=$!

# ---- wait for "Ready in" so we can hit the server ---------------------------
echo "→ Waiting for dev server to be ready (max 60s)…"
for i in $(seq 1 60); do
  if grep -q "Ready in" "${LOG_FILE}" 2>/dev/null; then
    break
  fi
  if ! kill -0 "${DEV_PID}" 2>/dev/null; then
    echo "❌ Dev server exited before becoming ready. Last 20 log lines:" >&2
    tail -20 "${LOG_FILE}" >&2
    exit 1
  fi
  sleep 1
done

if ! grep -q "Ready in" "${LOG_FILE}" 2>/dev/null; then
  echo "❌ Dev server did not report Ready in 60s. Last 20 log lines:" >&2
  tail -20 "${LOG_FILE}" >&2
  exit 1
fi

# ---- trigger Payload init ---------------------------------------------------
# The first request to any route causes Next to spin up Payload, which in turn
# runs drizzle-kit push against the configured DB (because the dev server has
# NODE_ENV=development, the push branch of payload.config.ts fires).
#
# We hit `/admin/api/users` rather than `/`: the homepage falls back to
# bundled copy if any CMS reader errors, so it can return 200 even when the
# DB is broken. The admin users API forces Payload to actually query, which
# surfaces real schema errors loudly.
echo "→ Triggering Payload init with one HTTP request"
HTTP_CODE="$(curl -s -o /dev/null -w '%{http_code}' "http://localhost:${PORT}/admin/api/users")"
echo "→ Dev server responded HTTP ${HTTP_CODE}"

# Give drizzle-kit a beat to finish any in-flight DDL after the request
# returns. The marker line only appears when there was an actual diff to
# push — a no-op sync produces no marker — so we wait on a fixed window
# instead of grepping for a specific string.
echo "→ Allowing 5s for drizzle-kit to finish any push work…"
sleep 5

# ---- check for schema / connection errors ---------------------------------
# Anything in this list means the sync did not work and the DB is still
# out of step with the code. Surface the full log so the operator can act.
if grep -E "ECONNREFUSED|password authentication failed|cannot connect to Postgres|column .* does not exist|relation .* does not exist|Failed query|payloadInitError" "${LOG_FILE}" 2>/dev/null; then
  echo "" >&2
  echo "❌ Schema sync produced errors. Full log:" >&2
  echo "----------------------------------------------------------------" >&2
  cat "${LOG_FILE}" >&2
  echo "----------------------------------------------------------------" >&2
  exit 1
fi

# Did drizzle-kit actually run? The "Pulling schema" marker is its standard
# progress line — it appears whether or not there were diffs to apply.
if grep -q "Pulling schema from database" "${LOG_FILE}" 2>/dev/null; then
  echo "✓ Schema sync complete — drizzle-kit ran against the DB."
else
  echo "✓ Schema sync complete — Payload init succeeded (push may have been a no-op)."
fi
